import styles from "./PrivacyPolicy.module.css";
import Header from "../../components/Header/Header";

const PrivacyPolicy = () => {
  return (
    <>
      <Header title="Privacy Policy" />
      <div className={`${styles.container} mx-auto px-4 py-8`}>
        <h1 className="text-3xl font-semibold mb-2 text-center">
          Privacy Policy
        </h1>
        <p className={`${styles.lastupdated} mb-4 text-center`}>
          Last updated: November 08, 2025
        </p>

        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>

        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="font-semibold text-2xl my-4">
          Interpretation and Definitions
        </h2>

        <h3 className="font-medium text-xl underline">Interpretation</h3>
        <p>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="font-medium text-xl underline">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className={`${styles.list} list-disc ml-6`}>
          <li>
            <b>Account</b> means a unique account created for You to access our
            Service or parts of our Service.
          </li>
          <li>
            <b>Affiliate</b> means an entity that controls, is controlled by, or
            is under common control with a party, where &quot;control&quot;
            means ownership of 50% or more of the shares, equity interest or
            other securities entitled to vote for election of directors or other
            managing authority.
          </li>
          <li>
            <b>Company</b> (referred to as either &quot;the Company&quot;,
            &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement)
            refers to The Green School International.
          </li>
          <li>
            <b>Cookies</b> are small files that are placed on Your computer,
            mobile device or any other device by a website, containing the
            details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <b>Country</b> refers to: Assam, India
          </li>
          <li>
            <b>Device</b> means any device that can access the Service such as a
            computer, a cell phone or a digital tablet.
          </li>
          <li>
            <b>Personal Data</b> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <b>Service</b> refers to the Website.
          </li>
          <li>
            <b>Service Provider</b> means any natural or legal person who
            processes the data on behalf of the Company.
          </li>
          <li>
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <b>Website</b> refers to The Green School International, accessible
            from{" "}
            <a className={styles.link} href="https://greenschoolguwahati.com/">
              https://greenschoolguwahati.com/
            </a>
          </li>
          <li>
            <b>You</b> means the individual accessing or using the Service, or
            the company, or other legal entity on behalf of which such
            individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="font-medium text-xl underline mt-2">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="font-medium text-base underline mt-2">
          Types of Data Collected
        </h3>

        <h4 className="font-medium text-base underline mt-2">Personal Data</h4>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className={`${styles.list} list-disc ml-6`}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="font-medium text-base underline mt-2">Usage Data</h4>

        <h3 className="font-medium text-xl underline mt-2">
          Tracking Technologies and Cookies
        </h3>
        <p>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies We
          use include beacons, tags, and scripts to collect and track
          information and to improve and analyze Our Service.
        </p>

        <p>
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the Cookies
          section of our Privacy Policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Use of Your Personal Data
        </h3>
        <p>
          The Company may use Personal Data for a number of purposes including
          to provide and maintain our Service, to manage Your Account, to
          perform a contract, to contact You, to provide You with news and
          offers, and to manage Your requests, as described in detail in the
          full policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Retention of Your Personal Data
        </h3>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Transfer of Your Personal Data
        </h3>
        <p>
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Delete Your Personal Data
        </h3>
        <p>
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You. You may update, amend,
          or delete Your information at any time by signing in to Your Account,
          if you have one.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Children&apos;s Privacy
        </h3>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Links to Other Websites
        </h3>
        <p>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Changes to this Privacy Policy
        </h3>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>

        <h3 className="font-medium text-xl underline mt-2">Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us by visiting this page on our website:{" "}
          <a
            className={`${styles.link} underline`}
            href="https://greenschoolguwahati.com/contact"
          >
            https://greenschoolguwahati.com/contact
          </a>
        </p>
      </div>
    </>
  );
};

export default PrivacyPolicy;
