import { useEffect } from "react";
import styles from "./PrivacyPolicy.module.css";
import Header from "../../components/Header/Header";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Header title="Privacy Policy" />
      <div className={`${styles.container} mx-auto px-4 py-8`}>
        <h1 className="text-3xl font-semibold mb-2 text-center">
          Privacy Policy
        </h1>
        <p className={`${styles.lastupdated} mb-4 text-center`}>
          Last updated: November 08, 2025
        </p>

        <p>
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use the
          service and explains your privacy rights and how the law protects you.
        </p>

        <p>
          We use your personal data to provide and improve the service. By using
          the service, you agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="font-semibold text-2xl my-4">
          Interpretation and Definitions
        </h2>

        <h3 className="font-medium text-xl underline">Interpretation</h3>
        <p>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. These definitions shall have the same
          meaning whether they appear in singular or plural form.
        </p>

        <h3 className="font-medium text-xl underline">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className={`${styles.list} list-disc ml-6`}>
          <li>
            <b>Account</b> means a unique account created for you to access our
            service or parts of our service.
          </li>
          <li>
            <b>Affiliate</b> means an entity that controls, is controlled by, or
            is under common control with a party. “Control” means ownership of
            50% or more of the shares, equity interest, or other securities
            entitled to vote for the election of directors or other managing
            authority.
          </li>
          <li>
            <b>Company</b> (referred to as “the Company”, “we”, “us”, or “our”
            in this Agreement) refers to The Green School International.
          </li>
          <li>
            <b>Cookies</b> are small files placed on your computer, mobile
            device, or any other device by a website, containing details of your
            browsing history and other uses.
          </li>
          <li>
            <b>Country</b> refers to Assam, India.
          </li>
          <li>
            <b>Device</b> means any device that can access the service such as a
            computer, mobile phone, or digital tablet.
          </li>
          <li>
            <b>Personal Data</b> means any information relating to an identified
            or identifiable individual.
          </li>
          <li>
            <b>Service</b> refers to the website.
          </li>
          <li>
            <b>Service Provider</b> means any natural or legal person who
            processes data on behalf of the company.
          </li>
          <li>
            <b>Usage Data</b> refers to data collected automatically, either
            generated by the use of the service or from the service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <b>Website</b> refers to The Green School International, accessible
            from{" "}
            <a className={styles.link} href="https://greenschoolguwahati.com/">
              https://greenschoolguwahati.com/
            </a>
          </li>
          <li>
            <b>You</b> means the individual accessing or using the service, or
            the company or other legal entity on whose behalf the individual is
            accessing or using the service, as applicable.
          </li>
        </ul>

        <h2 className="font-medium text-xl underline mt-2">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="font-medium text-base underline mt-2">
          Types of Data Collected
        </h3>

        <h4 className="font-medium text-base underline mt-2">Personal Data</h4>
        <p>
          While using our service, we may ask you to provide certain personally
          identifiable information that can be used to contact or identify you.
          Personally identifiable information may include, but is not limited
          to:
        </p>
        <ul className={`${styles.list} list-disc ml-6`}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, state, province, ZIP/postal code, city</li>
          <li>Usage data</li>
        </ul>

        <h4 className="font-medium text-base underline mt-2">Usage Data</h4>

        <h3 className="font-medium text-xl underline mt-2">
          Tracking Technologies and Cookies
        </h3>
        <p>
          We use cookies and similar tracking technologies to track activity on
          our service and store certain information. Tracking technologies
          include beacons, tags, and scripts to collect and analyze information
          and to improve our service.
        </p>

        <p>
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the cookies
          section of our Privacy Policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Use of Your Personal Data
        </h3>
        <p>
          The Company may use personal data for several purposes including to
          provide and maintain our service, to manage your account, to perform a
          contract, to contact you, to provide you with news and offers, and to
          manage your requests, as described in the full policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Retention of Your Personal Data
        </h3>
        <p>
          The Company will retain your personal data only for as long as
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Transfer of Your Personal Data
        </h3>
        <p>
          Your information, including personal data, is processed at the
          Company&apos;s operating offices and any other locations where the
          parties involved in the processing are located.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Delete Your Personal Data
        </h3>
        <p>
          You have the right to delete or request assistance in deleting the
          personal data that we have collected about you. You may update, amend,
          or delete your information at any time by signing in to your account,
          if you have one.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Children&apos;s Privacy
        </h3>
        <p>
          Our service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from individuals
          under the age of 13.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Links to Other Websites
        </h3>
        <p>
          Our service may contain links to other websites that are not operated
          by us. If you click a third-party link, you will be directed to that
          site. We strongly advise you to review the Privacy Policy of every
          website you visit.
        </p>

        <h3 className="font-medium text-xl underline mt-2">
          Changes to This Privacy Policy
        </h3>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the updated Privacy Policy on this page.
        </p>

        <h3 className="font-medium text-xl underline mt-2">Contact Us</h3>
        <p>
          If you have any questions about this Privacy Policy, you can contact
          us by visiting this page on our website:{" "}
          <a
            className={`${styles.link} underline`}
            href="https://greenschoolguwahati.com/contact"
          >
            https://greenschoolguwahati.com/contact
          </a>
        </p>
      </div>
    </>
  );
};

export default PrivacyPolicy;
