class TransferCertificateUtils {
  static studentFileNames = [
    "Aaditya_Agarwal",
    "Aadrika_Thapa",
    "Aaradhya_Agarwal",
    "Aarav_Sharma",
    "Aarin_Mohan",
    "Aarna_Jindal",
    "Aarohan_Kumar_Nath",
    "Aditri_Das",
    "Aditya_Mishra",
    "Advik_Patel",
    "Aliya_Parbeen",
    "Ansh_Raj",
    "Arhaan_Zaman",
    "Arpit_Giri",
    "Arpita_Tayal",
    "Aryan_Verma",
    "Avinab_Saha",
    "Ayanav_Baruah",
    "Ayushi_Tiwari",
    "Ayushmaan_Nath",
    "Bornil_Jyoti_Singh",
    "Chaitanya_Tyagi",
    "Darsh_Chokhani",
    "Debangshi_Hazarika",
    "Debanshi_Ghosh",
    "Deleena_Kashyap",
    "Deveshi_Agarwal",
    "Dhaani_Kalita",
    "Dhiru_Mohan_Sinha",
    "Dia_Dulom",
    "Diyan_Barman",
    "Drishti_Raut",
    "Gyan_Neev_Shyam",
    "Gyandeep_Das",
    "Hangsavi_Nath",
    "Harshe_Jain",
    "Hridaan_Hriday",
    "Hridhaan_Bhagowati",
    "Hrishita_Nath",
    "Jaishnu_Jonak_Gogoi",
    "Jay_Bafna",
    "Jay_Mazumdar",
    "Jeenal_Agarwal",
    "Kabir_Singh",
    "Karishmita_Dutta",
    "Krishiv_Rabha",
    "Krishnangshu_Kumar_Malakar",
    "Kristi_Hazarika",
    "Kritarth_Kaustav",
    "Lasmi_Narzary",
    "Linisha_Dulom",
    "Mairaa_Shyam",
    "MD_Arhan_Alam",
    "Mehar_Tayal",
    "Milind_Agarwalla",
    "navi-Sonowal_Talukdar",
    "Nayaneeka_Chakrabarty",
    "Nikhil_Ray_Boro",
    "Ningjoanna-Vaiphei",
    "Niobee_Shivam",
    "Niyusha_Bothra",
    "P_Hanspreet",
    "Pangkhi_Priya_Gogoi",
    "Parijan_Kumar_Mahato",
    "Rahul_Kalita",
    "Rajat_Sharma",
    "Ranjit_Haloi",
    "Reyansh_Barua",
    "Riddhi_Shome",
    "Rishaan_Thakur",
    "Riyaan_Tanveer",
    "S_Devansh_Meitei",
    "Saksham_Mishra",
    "Sandip_Nath",
    "Shivank_Neil_Saikia",
    "Shrainee_Langthasa",
    "Shreyank_Sinha",
    "Soumyadeep_Mahato",
    "Sreejani_Das",
    "Subh_Kumar",
    "Taneesha_Jain",
    "Tanishq_Sureka",
    "Tanmay_Tyagi",
    "Tejaswini_Raj",
    "Thavnesh_Singh",
    "Vaibhav_Surana",
    "Vivaansh_Singh_Padiya",
    "Zavian_Junaid",
  ];

  static formatFileNameToName(fileName) {
    return fileName.split("_").join(" ");
  }

  static generateCertificateURL(fileName) {
    return `https://api.greenschoolguwahati.com/transfer_certificates/${fileName}.pdf`;
  }
}

export default TransferCertificateUtils;
